stages:
  - build

build:
  stage: build
  image: registry.gitlab.com/naoki_maeda/sylphide
  services:
    - name: docker:19.03.12-dind
      alias: docker
  variables:
    # TODO: Enable TLS
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - cross build --target x86_64-unknown-linux-gnu
    - cross build --target x86_64-pc-windows-gnu
