stages:
  - build

build:
  stage: build
  image: $CI_REGISTRY_IMAGE
  services:
    - name: docker:19.03.12-dind
      alias: docker
  variables:
    # TODO: Enable TLS
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - cross build --target $BUILD_TARGET
  parallel:
    matrix:
      - BUILD_TARGET: [x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu]
  rules:
    # When the master / develop branch is changed
    - if: $CI_COMMIT_BRANCH == "master" ||
          $CI_COMMIT_BRANCH == "develop"
      when: always
    # When the MR target is the master / develop branch
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || 
          $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"
      when: always
    # When the MR source is a feature branch
    - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ "/^feature"
      when: manual
      allow_failure: true
